CREATE UNIQUE INDEX IDX_LOGIN_ID_UNIQUE ON USER_PROFILE(LOGIN_ID);

CREATE INDEX IDX_CPN_TIME ON CONSUMPTION(CPN_TIME);

CREATE INDEX IDX_INCOMING_DATE ON INCOMING(INCOMING_DATE);

CREATE UNIQUE INDEX UDX_INCOMING_BATCHNUM ON INCOMING(BATCH_NUM);

CREATE UNIQUE INDEX UDX_CONSUMPTION_BATCHNUM ON CONSUMPTION(BATCH_NUM);

CREATE INDEX IDX_ACCOUNT_AUDIT_BATCHNUM ON ACCOUNT_AUDIT(BATCH_NUM);